Delete appointment
AY2324S1-CS2103T-W09-3/tp pull request #52
Opened 2023-10-15 12:19 UTC by Bryan-Goh

2023-10-16 05:51 UTC, simbayippy commented on docs/UserGuide.md
> +* The command is case-sensitive. E.g. delete_appt INDEX /appt 3 will not work
Should this be Delete_appt?

2023-10-16 09:28 UTC, tohpinren requested changes
Please add newline in following files:
<img width="1071" alt="image" src="https://github.com/AY2324S1-CS2103T-W09-3/tp/assets/64828959/bfc01da8-c3c7-47b2-9c5f-b2f03cfdb6a7">

2023-10-16 09:43 UTC, Bryan-Goh commented on docs/UserGuide.md
> +* The command is case-sensitive. E.g. delete_appt INDEX /appt 3 will not work
should be delete_appt

2023-10-16 10:53 UTC, simbayippy commented on docs/UserGuide.md
> +* The command is case-sensitive. E.g. delete_appt INDEX /appt 3 will not work
the negative and positive formats appear to be the same, both of delete_appt

2023-10-17 05:08 UTC, tohpinren approved these changes

2023-10-17 05:08 UTC, merged